new_tab .plan
cd ~/Documents/.plan
launch zsh

new_tab habitmap
cd ~/Documents/projects/habitmap
launch zsh

new_tab server
cd ~/Documents/projects/habitmap
launch zsh

new_tab db
cd ~/Documents/projects/habitmap
launch zsh

new_tab dotfiles
cd ~/dotfiles
launch zsh
